### ISSUE TITLE
Don't create a well known user 'fbx'

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/freedom-maker#12]
We now have the ability to create (also change password, rename, activate/deactivate) POSIX users during Plinth first run.  We should look forward to removing the creation of fbx user from freedom-maker.

A command line tool to create such a user inside an image may be good to have to ensure that in the case that Plinth is not accessible, people have a work around.

**Comment by jvalleroy** [comment]
This is fixed with #37.
