### ISSUE TITLE
Inside images, create a file based flag to indicate they are FreedomBox images

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/freedom-maker#123]
Discussion here https://github.com/freedombox/Plinth/pull/1003 indicates at the need for a creating a file called `/var/lib/freedombox/is_freedombox_image` in each image that is created. This will be used to ensure that scripts like networks setup which does not need to run on Debian based installs works without causing harm.

**Comment by jvalleroy** [comment]
Done in #125.
