### ISSUE TITLE
Cannot build image with btrfs

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/freedom-maker#16]
This is probably not an issue in freedom-maker, but it's preventing me from building images with btrfs.
```
$ make virtualbox
mkdir -p build
ARCHITECTURE=i386 DESTINATION=hdd MACHINE=virtualbox SOURCE=false MIRROR=http://http.debian.net/debian SUITE=sid OWNER=1000 BUILD_MIRROR=http://http.debian.net/debian ENABLE_NONFREE=no IMAGE_SIZE=4G taskset 0x01 bin/mk_freedombox_image build/freedombox-unstable_2015-05-24_virtualbox-i386-hdd
Building virtualbox FreedomBox for i386.
starting vendor/vmdebootstrap/vmdebootstrap
Creating disk image
Creating partitions
Installing MBR
Creating filesystem btrfs
EEEK! Something bad happened...
command failed: ['mkfs', '-t', 'btrfs', '/dev/mapper/loop0p1']

mkfs: failed to execute mkfs.btrfs: No such file or directory

Cleaning up
ERROR: command failed: ['mkfs', '-t', 'btrfs', '/dev/mapper/loop0p1']

mkfs: failed to execute mkfs.btrfs: No such file or directory

Makefile:109: recipe for target 'virtualbox-i386' failed
make: *** [virtualbox-i386] Error 1
```
If I switch to ext4, then the image will build ok. Is anyone else seeing this error?

**Comment by SunilMohanAdapa** [comment]
You will need to have `btrfs-tools` installed in your build system.  The build fails at the when preparing the image partitions.  So, this is not inside the chroot environment and hence has nothing to do with packages we are installing inside the image.

The requirement for `btrfs-tools` is documented in `To Make It` section in the README for freedom-maker.  So, possibly, no bug here.  Please verify my theory and close the issue.

**Comment by jvalleroy** [comment]
@SunilMohanAdapa Yes, I have btrfs-tools installed:
```
$ mkfs.btrfs --version
mkfs.btrfs, part of btrfs-progs v4.0
```

**Comment by SunilMohanAdapa** [comment]
I upgaded to the latest version of `btrfs-tools` (4.0-2) and the problem appeared for me while it was working with earlier version of `btrfs-tools` (3.17-1.1).

**Comment by SunilMohanAdapa** [comment]
`mkfs.btrfs` seems to have moved from `/sbin` to `/bin` during the version upgrade.  That seems to have caused the issue. Creating a symlink `/sbin' fixed the issue for me.  This is either to fixed in vmdebootstrap or mkfs or btrtfs-utils.

**Comment by jvalleroy** [comment]
I believe this has been fixed, at least for unstable. I'm able to build images on a fresh install without creating the symlink.
