### ISSUE TITLE
Use official debian archives only

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/freedom-maker#2]
Depends on:

- Deliver FreedomBox Setup Debian Package
- Deliver FreedomBuddy Debian Package

This is probably already completed.  If so, we can confirm and close.

**Comment by SunilMohanAdapa** [comment]
I agree from the current state of things, this bug can be closed.  Is there a reason you re-opened the bug?

**Comment by NickDaly** [comment]
I just wanted to make sure the fbx-setup package was available before I closed the bug, and yeah, it's available, refer to:

https://packages.debian.org/search?keywords=freedombox%2Dsetup

**Comment by SunilMohanAdapa** [comment]
I just noticed that the preseed files in freedombox-setup package are still adding custom repositories.  Perhaps I will raise another bug for freedombox-setup package on that.
