### ISSUE TITLE
Create a Debian package

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/freedom-maker#29]
Should we try to get freedom-maker into Debian?

**Comment by SunilMohanAdapa** [comment]
I think this is good to do.  This is the last piece of FreedomBox that is not in Debian.  Although end users don't use it, it is certainly nice to have.  It could fix the following problems:

- Wrong dependencies during build.  Recently, bashrc reported that building on a particular machine lead to a bad build.
- Smooth experience for people looking to build their own images (especially if we support large number of hardware boards).

**Comment by jvalleroy** [comment]
Here's a few things that will be needed:
- [ ] Upstream the btrfs support patch for vmdebootstrap.
- [ ] Should be able to "make install" and run freedom-maker from the installed location.

**Comment by SunilMohanAdapa** [comment]
Upstreaming of btrfs patch is complete.

**Comment by jvalleroy** [comment]
On IRC, Petter suggested merging freedom-maker into the freedombox-setup source package. (But not part of the f-s binary package.) Would there be any issues with this approach?

**Comment by SunilMohanAdapa** [comment]
On 03/04/2016 09:44 PM, James Valleroy wrote:
> On IRC, Petter suggested merging freedom-maker into the freedombox-setup
> source package. (But not part of the f-s binary package.) Would there be
> any issues with this approach?
> 

I don't foresee any problems taking this approach.  However, I don't see
any major advantages in doing this.

Conceptually they are doing two completely different things.
freedom-maker does not have to be FreedomBox specific at all (except for
the choice of installing freedombox-setup package by default).  The
functionality of freedom-maker may get absorbed into vmdebootstrap,
debootstrap, flash-kernel etc.

freedom-maker is:

- A vmdebootstrap launcher.  This may be taken into vmdebootstrap.  Very
useful for building Debian images for various hardware.

- Hardware setup script.  Properly done, this is just two lines using
flash-kernel.

- Customize script:

  o Firmware writing in customize script.  This firmware writing part
that vmdebootstrap may be interested in doing (just like it does grub).

  o Eatmydata in customize. This is a larger concern for vmdebootstrap too.

  o Apt source setting.  vmdebootstrap already has some of this
functionality.

  o User creation.  Already part of vmdebootstrap, I believe.

  o Running freedombox-setup.  This is the only part FreedomBox
specific.  This is very minimal.

-- 
Sunil

**Comment by jvalleroy** [comment]
Packaging added in #104, and uploaded to unstable.
