### ISSUE TITLE
Beaglebone Black failed to booting up by using u-boot (2016-01)

### ISSUE THREAD

**Issue by tonghuix** [freedombox/freedom-maker#49]
Today I just upgrade and flash my eMMC's Debian Jessie to latest 201601 from BBB official. This upgrade version updated u-boot to 2016-01 as well. It could boot up eMMC Debian, but SD card Freedombox failed. It stuck at "Starting Kernel..." from serial port watching.  

However, I recreate the freedombox sdcard, it could boot up and finish setup, but after it reboot, failed again. I believe it should be a bug. 

And I still testing for sure. Freedombox version 0.7 12-13

Following are the serial output:

````
U-Boot SPL 2016.01-00001-g4eb802e (Jan 13 2016 - 11:14:31)
Trying to boot from MMC
bad magic

U-Boot 2016.01-00001-g4eb802e (Jan 13 2016 - 11:14:31 -0600), Build: jenkins-github_Bootloader-Builder-313

       Watchdog enabled
I2C:   ready
DRAM:  512 MiB
Reset Source: Global warm SW reset has occurred.
Reset Source: Power-on reset has occurred.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Using default environment

Net:   <ethaddr> not set. Validating first E-fuse MAC
cpsw, usb_ether
Press SPACE to abort autoboot in 2 seconds
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
1577 bytes read in 17 ms (89.8 KiB/s)
## Executing script at 80000000
3452904 bytes read in 211 ms (15.6 MiB/s)
31013 bytes read in 256 ms (118.2 KiB/s)
13567447 bytes read in 792 ms (16.3 MiB/s)
Booting Debian 4.2.0-1-armmp from mmc 0:1...
Kernel image @ 0x82000000 [ 0x000000 - 0x34afe8 ]
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Ramdisk to 8f30f000, end 8ffff5d7 ... OK
   Loading Device Tree to 8f304000, end 8f30e924 ... OK

Starting kernel ...
````

**Comment by tonghuix** [comment]
I tested u-boot 2015-12 not working as will.

**Comment by SunilMohanAdapa** [comment]
On 02/02/2016 07:34 AM, Tong Hui wrote:
> Today I just upgrade and flash my eMMC's Debian Jessie to latest 201601
> from BBB official This upgrade version updated u-boot to 2016-01 as well
> It could boot up eMMC Debian, but SD card Freedombox failed It stuck at
> "Starting Kernel" from serial port watching
> 
> However, I recreate the freedombox sdcard, it could boot up and finish
> setup, but after it reboot, failed again I believe it should be a bug
> 

Another user reported the same issue recently that after the first
reboot, image was not booting anymore.  I wrote:

"If first boot setup is causing the further boots to fail then most
likely the flash-kernel script in freedombox-setup is the reason.  You
can create a fresh SD card, mount it then disable by the flash-kernel
script by creating a empty file in /var/freedombox/dont-tweak-kernel."

That worked.  We didn't yet do debugging on why the flash kernel script
was not working.

-- 
Sunil

**Comment by tonghuix** [comment]
Thank you very much! It solved.

**Comment by tonghuix** [comment]
Sooorry...

I recreate uboot 201601 and cannot reboot after first sd card init setup.

**Comment by SunilMohanAdapa** [comment]
Doing #52 may fix this issue.  I may have an experimental patch soon.

**Comment by SunilMohanAdapa** [comment]
I just investigated a bit (without actually having a BBB to do hands-on). I have two possible workarounds:

1. Mount the SD card on a machine and rename away the boot.scr file. Try to boot.

2. Press the S2 switch and reboot the BBB (switch must be pressed while booting). Try this also with 1).

Here is what I found:

- You are booting from on-board eMMC first. There the u-boot version is "U-Boot 2016.01-00001-g4eb802e (Jan 13 2016 - 11:14:31 -0600)". This is not be found on FreedomBox/Debian. Pressing the S2 switch will change the boot order and boot from MMC directly.

- This u-boot is trying to load boot script from the MMC (correctly).

- boot.scr file has been created by the flash-kernel script after upgrade. FreedomBox's usual way of booting is from uEnv.txt file which is still there. I don't see any problem with the boot.scr file but in case this the problem, removing the file should make u-boot load the uEnv.txt.

- I have noticed that after the package upgrade process, u-boot which on SD card is intact. So, pressing S2 switch to make it boot from here.

Let me know how it goes. Further logs will be immensely helpful.

**Comment by SunilMohanAdapa** [comment]
Here is a dump of my understanding currently which is the basis of my workaround suggestions.
![understanding](https://cloud.githubusercontent.com/assets/1535496/13085081/85cf030c-d502-11e5-97b6-85f4fe60abcc.png)

**Comment by SunilMohanAdapa** [comment]
I got the BeagleBone Black to work with the latest build of FreedomBox.  The kernel version is 4.5 but I believe the problem/resolution apply to all latest kernel upgrades and builds.

1. The inbuilt eMMC and the MMC card are getting assigned number arbitrarily on boot with recent kernels. So, /dev/mmcblk0 is eMMC and /dev/mmcblk1 is MMC card, but only sometimes.  Other times, they are swapped.  It is not predictable and I noticed that it can change on reboot.  Instead of having root=/dev/mmcblk0p2 if I give root=UUID=xxxx (ID of the root filesystem) then it works.
1. I believe the kernel not printing any messages is because of not having `console=ttyO0,115200n8` in boot arguments to the kernel.
1. I have also tried using flash-kernel script and it works too.  Here too, I had to give `LINUX_KERNEL_CMDLINE="root=UUID=2da8696d-0f83-419e-8507-e6ea8d7a1720 rootwait coo
nsole=tty0 console=ttyO0,115200n8"` in `/etc/default/flash-kernel` to make it work.

Based on this, I am looking to make a patch to freedom-maker to use flash-kernel and fix the issue by specifying a more explicit root= argument.

**Comment by SunilMohanAdapa** [comment]
The new nightly images boot well with BeagleBone Black with linux 4.5 kernel.

**Comment by tonghuix** [comment]
Hi, @SunilMohanAdapa 
where can I find and download the nightly build image?

**Comment by SunilMohanAdapa** [comment]
On 05/28/2016 07:31 PM, Tong Hui wrote:
> Hi, @SunilMohanAdapa <https://github.com/SunilMohanAdapa>
> where can I find and download the nightly build image?

Please download from here:
http://ftp.skolelinux.org/pub/freedombox/nightly/

-- 
Sunil
