### ISSUE TITLE
Failed to boot up after apt-get upgrade (Beaglebone Black)

### ISSUE THREAD

**Issue by tonghuix** [freedombox/freedom-maker#51]
To make it more quickly upgrade, I executed apt-get upgrade via ssh. A large number of packages upgraded, including kernel and uboot. 

However, after upgrade and reboot, it cannot boot up, no any additional output.

**Comment by SunilMohanAdapa** [comment]
I believe this is a duplicate of #49 . When a newer kernel is installed, flask-kernel script is triggered and this is causing issues with boot.
