### ISSUE TITLE
Expand Image to Fill SD Card on First Boot

### ISSUE THREAD

**Issue by NickDaly** [freedombox/freedom-maker#58]
The last thing F-M should do before rebooting is to sync data and then resize the image to fill remaining space on the device it's currently on, if it's the last partition and there's more than 5% of the image's current size free.

If it's not the last partition, we probably aren't on a F-M-built image.  If there's less than 5% more space available, it's probably not worth the risk/effort.

**Comment by SunilMohanAdapa** [comment]
On 03/07/2016 12:08 AM, Nick Daly wrote:
> The last thing F-M should do before rebooting is to sync data and then
> resize the image to fill remaining space on the device it's currently
> on, if it's the last partition and there's more than 5% of the image's
> current size free.
> 
> If it's not the last partition, we probably aren't on a F-M-built image.
> If there's less than 5% more space available, it's probably not worth
> the risk/effort.

That is a good plan.  We could perhaps use GNU Parted to expand the
partition and the file system in a relatively safe and easy to implement
way.

The first boot scripts are part of freedombox-setup, so, I guess this
should go there.  One thing we should take into account is that when
people on regular Debian systems install freedombox-setup, it should not
effect them.  Perhaps adding this to Plinth first-boot is also a
possibility.

-- 
Sunil

**Comment by SunilMohanAdapa** [comment]
Currently, Plinth has an option to expand the root disk live from new 'Disks' system settings menu item.  I believe this sufficient to consider this issue closed.  Further interface improvements can be tracked in Plinth.
