### ISSUE TITLE
Consider dropping non-free from Dreamplug image

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/freedom-maker#67]
Dreamplug requires non-free firmware only for the built-in wifi. At first, it was the only hardware target with wifi supported, so this made sense for testing purposes. But since we can use wifi dongles with free firmware now, we could drop the non-free parts. Also I suspect our Dreamplug user base is very small, so it should not have much impact.

**Comment by SunilMohanAdapa** [comment]
I agree.
