### ISSUE TITLE
Use Debian kernel/u-boot for Raspberry Pi 2/3

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/freedom-maker#68]
It is now possible to use Raspberry Pi 2/3 with mainline/Debian kernel and mainline/Debian u-boot.  flash-kernel script also supports it properly. I got it work with nicely. Modify freedom-maker to not use the outside script for upgrading kernel and instead rely on Debian kernels, u-boot and flash-kernel.

This means the we can start using `btrfs` with Rasbperry Pi 2/3 also.

[Free boot firmware](https://github.com/christinaa/rpi-open-firmware/issues) is also getting ready.

Here is my partition table

```
Device         Boot  Start      End  Sectors   Size Id Type
/dev/mmcblk0p1 *         1   238281   238281 116.4M  e W95 FAT16 (LBA)
/dev/mmcblk0p2      649216 15523839 14874624   7.1G 83 Linux
/dev/mmcblk0p3 *    239616   649215   409600   200M 83 Linux
```

Flash kernel configuration

```
root@freedombox:/boot# cat /etc/default/flash-kernel 
LINUX_KERNEL_CMDLINE=""
LINUX_KERNEL_CMDLINE_DEFAULTS=""
```

```
root@freedombox:/boot# cat /etc/flash-kernel/machine 
Raspberry Pi 2 Model B
```

Contents of boot

```
root@freedombox:~# find /boot/
/boot/config-4.5.0-2-armmp  --> Kernel configuration, installed by linux-image-armmp
/boot/vmlinuz-4.5.0-2-armmp  --> Kernel, installed by linux-image-armmp
/boot/boot.scr  --> u-boot boot script, generated by flash-kernel
/boot/System.map-4.5.0-2-armmp  --> Symbol table, installed by linux-image-armmp
/boot/initrd.img-4.5.0-2-armmp  --> Initial ram disk, generated by update-initramfs
/boot/dtbs/4.5.0-2-armmp/bcm2836-rpi-2-b.dtb  --> Device tree binary, copied by flash-kernel
/boot/firmware/bootcode.bin  --> Stage 2 boot loader, propietary blob
/boot/firmware/start.elf  --> GPU binary proprietary blob
/boot/firmware/fixup.dat  --> Use by start.elf, propietary blon
/boot/firmware/kernel.img  --> U-Boot, u-boot.bin file from package u-boot-rpi
```

Boot process ([see](http://elinux.org/RPi_Software)):
1. GPU loads first stage boot loader from ROM
2. First stage loader reads `bootcode.bin` from first partition of the SD card.  This is second stage boot loader.
3. Second state loader reads `start.elf` an ELF binary from SD card and runs it on GPU.
4. `start.elf` initializes CPU, loads `kernel.img` from SD card and runs it on CPU.  `fixup.dat` is also used here.
5. `kernel.img` is renamed u-boot binary.  Until this point, all the binaries must be in the first partition, which must be FAT filesystem. Debian prefers to mount this partition on /boot/firmware instead of /boot because some of the flash-kernel and initramfs scripts fail during installation of kernel trying to create hard/soft links.
6. u-boot will look for all SD cards and all partitions with _bootable_ flag on them for `boot.scr`. The u-boot boot script.
7. `boot.scr` will load kernel, initrd and DTB files from the same partition that it was loaded from and from the same directory prefix, such as /boot, it was loaded from.
8. initrd will contain the UUID of the root device picked up from /etc/fstab during initramfs generation.  This root is mounted by initrd and boot continues.

**Comment by jvalleroy** [comment]
Done for RPi2. RPi3 is tracked in #95. So I think this can be closed.
