### ISSUE TITLE
beaglebone black images too large to fit on eMMC

### ISSUE THREAD

**Issue by chrysn** [freedombox/freedom-maker#73]
the images for beaglebone (tested with latest daily
freedombox-unstable-free_daily_beaglebone-armhf.img.xz, timestamped
2016-05-27) are unpacked exactly 4gb in size.

in order to flash them directly onto the builtin eMMC (eg. using
BBBlfs), they should be smaller -- `lsblk -b` on the running system
reports mmcblk1 to be 386148288 bytes long. (the device is advertised as
4gb, which i'd figure would even mean 4*1024^3 bytes; i have no idea
about where the missing bytes are, but at least BBBlfs and the running
freedombox seem to agree on the size. there are some
/dev/mmcblk1boot[01] devices around which i can't make heads and tails
of, but they appear much smaller.)

as a workaround, i flashed the image, edited the partition table to fit,
and then resized the btrfs (which to my surprise just worked and did not
report errors on the subsequent scrub), but that's something i'd prefer
not to rely on.

please consider reducing the image size; even with the decreased size,
there's plenty of headroom in the image.

(this was previously reported as <https://bugs.debian.org/828839>, but that package doesn't exist (yet?)).

**Comment by SunilMohanAdapa** [comment]
Thank you for the detailed bug report.

I proposed a change #80 to reduce the size of the images to 3800MB.  I hope that fits all the "4GB" SD cards out there. We have recently introduced a feature to easily expand the disk partitions to full size of SD card from the Plinth web interface after first boot.  This should alleviate concerns of not using full disk space.

Apart from this report some other people also have reported that they were unable to use 4GB SD cards.  Note that 4GB as promised by disk manufacturers is 4\*1000^3.  Also, it is more common to mean 4[GiB](https://en.wikipedia.org/wiki/Binary_prefix) = 4\*1024^3 and 4 GB = 4\*1000^3. I read that SD cards could also have less capacity than promised when compensating bad sectors.  But mostly I think the disk manufacturers are simply rounding up 3.9 GB etc. to 4 GB.
