### ISSUE TITLE
Use flash-kernel and Debian kernel for Raspberry Pi 2/3 images

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/freedom-maker#77]
After fixing #76 , we will have the ability to use Debian armmp kernel/initrd for booting Raspberry Pi 2/3.  Remove the current external script that downloads proprietary blobs.  This will make the images for Raspberry Pi 2/3 almost free (except the GPU boot firmware for which free replacement is under development).

**Comment by jvalleroy** [comment]
I think this is the same as #68:
Done for RPi2. RPi3 is tracked in #95.
