### ISSUE TITLE
Integrate Vagrant box generation into builder script

### ISSUE THREAD

**Issue by SunilMohanAdapa** [freedombox/freedom-maker#82]
It should be possible for us to build a vagrant box using freedom-maker main script.  We already have a script to build vagrant box from a virtualbox .vdi.  Integrate this script into the main script to be able to generate vagrant boxes like other images.

**Comment by sahithi-ihtihas** [comment]
To which file do i need to add the vagrant package ?

**Comment by jvalleroy** [comment]
@sahithi-ihtihas I have already implemented this change in #84 (waiting for review).

However some further work could be done to support other vagrant providers, besides virtualbox. For example, we could build a vagrant box for libvirt provider.

**Comment by jvalleroy** [comment]
Done with merge of #84.
