### ISSUE TITLE
Update default mirror and build-mirror

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/freedom-maker#91]
According to https://wiki.debian.org/DebianGeoMirror, httpredir.debian.org is discontinued, and deb.debian.org should be used.

Update the default options in freedom-maker to point to the current mirror URL.

**Comment by coderark** [comment]
working on it.

**Comment by SunilMohanAdapa** [comment]
I have merged the patch.

**Comment by SunilMohanAdapa** [comment]
I have built a new image with the patch applied and checked that build process and actions later are doing well.
